# Generated by Django 3.0.6 on 2020-05-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0003_auto_20200528_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='display_name',
            field=models.CharField(max_length=50),
        ),
    ]
